### ISSUE TITLE
système de recherche sur la home

### ISSUE THREAD

**Issue by Benoit-MINT** [Matva84/artbnb#17]
le système de recherche, pour être utile, gagnerait à avoir des critères de recherches : prix, catégorie ... car par mots clés, c'est difficilement actionnable

**Comment by Matva84** [comment]
Lors du clic sur la barre de recherche apparaissent les catégories, pays et les dates pour le moment sont cachées...

**Comment by Matva84** [comment]
Pour que ces champs de recherche apparaissent il faut faire un ctrl + maj + r de la page. Je changerai mes queryselector and co par des turbo-data vu dans le cours dernier.

**Comment by Benoit-MINT** [comment]
Ce que je constate :
- la recherche par mots clés fonctionne bien
- en revanche les autres critères ensuite ne sont pas pris en compte
- une recherche vide rend une liste vide

De ce que je vois dans le code, dans la méthode index du controller masterpieces, l'imbrication des "if" ne me semble pas correct. Je vais faire un test sur une nouvelle branche

**Comment by Benoit-MINT** [comment]
normalement c'est good, voir PR30 : https://github.com/Matva84/artbnb/pull/30

(reste à finir les critères de recherche par date), pas simple du tout je pense ...

**Comment by Benoit-MINT** [comment]
je vois que tout est good! https://github.com/Matva84/artbnb/pull/31
