### ISSUE TITLE
user model

### ISSUE THREAD

**Issue by Benoit-MINT** [Matva84/artbnb#2]
j'ai l'impression qu'il manque dans le modèle "user" les différents attributs de notre modèle de données : name, address, etc ... @Matva84  ?

**Comment by Matva84** [comment]
Hello Benoit, effectivement le modèle User a été génère automatiquement par devise, je n'y a pas touché donc pas de nom ni d'adresse, il faudra probablement faire une migration du coup 😉

**Comment by Benoit-MINT** [comment]
@Matva84  a fait le nécessaire, je ferme cette issue
